### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by GeorgeS2019** [GeorgeS2019/CesiumForGodot4#2]
---

## Godot [Proposal ](https://github.com/godotengine/godot-proposals/discussions/6913#discussion-5212560)for Cesium For Godot

Keep this issue open until the LInux and VS2022 build are addressed.

---

# **Why this issue is raised?** 
The **lessons learned** could be relevant for users attempting to ==> build for [**Linux**](https://github.com/Battle-Road-Labs/3D-Tiles-For-Godot/issues/84#issuecomment-2985278896).

### Linux build
https://github.com/jph6366/3D-Tiles-For-Godot
https://github.com/Battle-Road-Labs/3D-Tiles-For-Godot/issues/84#issuecomment-2948962920

---

## Build command not documented in the readme.md

`scons platform=windows arch=x64 compileTarget=extension target=template_release buildCesium=true`

---

History of troubleshooting Windows Build
https://github.com/Battle-Road-Labs/3D-Tiles-For-Godot/issues/84

---
### GIT_LFS_SKIP_SMUDGE (optional?)
> It may be necessary on some systems to set the **GIT_LFS_SKIP_SMUDGE** [environment variable.](https://github.com/CesiumGS/cesium-native/issues/1142#issuecomment-2987513434)

---
### CMAKE
> It may also still be helpful to stick to the[ latest CMake 3.x version and above CMake 4.x.](https://github.com/CesiumGS/cesium-native/issues/1142#issuecomment-2987517021)
DCMAKE_POLICY_VERSION_MINIMUM="3.5"

![Image](https://github.com/user-attachments/assets/229d71a7-c3a3-4f37-9b1c-ad85e631680b)

---
### vcpkg commit
> It seems to me like you are using an [out of date clone of vcpkg](https://github.com/CesiumGS/cesium-native/issues/1142#issuecomment-2904701062)

[2025.06.13](https://github.com/microsoft/vcpkg/releases/tag/2025.06.13)
https://github.com/microsoft/vcpkg/commit/dbe35ceb30c688bf72e952ab23778e009a578f18

This vbpkg **May 13th 2025** commit is using ktx 4.3.2 => windows build works with ktx 4.3.2, [**ktx 4.4.0 is not necessary**](https://github.com/Battle-Road-Labs/3D-Tiles-For-Godot/issues/84#issuecomment-2885036994)
- [solution](https://github.com/Battle-Road-Labs/3D-Tiles-For-Godot/issues/84#issuecomment-2904812830)
- ktx 4.4.0 remains not available (status June 20th 2025)

https://github.com/microsoft/vcpkg/blob/dbe35ceb30c688bf72e952ab23778e009a578f18/versions/baseline.json#L4279

---
### 3D-Tiles-For-Godot\cesium_godot\native
- Cesium Native
 - **v0.48.0**
- Commit 9549810
https://github.com/CesiumGS/cesium-native/commit/95498106dbac35de7ca87bc52c926a94b2091938

![Image](https://github.com/user-attachments/assets/c35bb516-0013-4fa8-a3b7-877549332615)

---

**Comment by GeorgeS2019** [comment]
### Work
`scons platform=windows arch=x64 compileTarget=extension target=template_release buildCesium=true`

---

### Not work
`scons platform=windows compiledb=true arch=x64 compileTarget=extension debug_symbols=true buildCesium=true`

<details>
<summary>Fail to build</summary>

```
Linking Static Library godot-cpp\bin\libgodot-cpp.windows.template_debug.x86_64.lib ...
Linking Shared Library godot3dtiles\bin\Godot3DTiles.windows.template_debug.x86_64.dll ...
CesiumGltfReader.lib(ImageDecoder.obj) : error LNK2019: unresolved external symbol __imp_ktxTexture_GetData referenced in function "public: static struct CesiumGltfReader::ImageReaderResult __cdecl CesiumGltfReader::ImageDecoder::readImage(class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::Ktx2TranscodeTargets const &)" (?readImage@ImageDecoder@CesiumGltfReader@@SA?AUImageReaderResult@2@AEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUKtx2TranscodeTargets@CesiumGltf@@@Z)
CesiumGltfReader.lib(ImageDecoder.obj) : error LNK2019: unresolved external symbol __imp_ktxTexture_GetDataSize referenced in function "public: static struct CesiumGltfReader::ImageReaderResult __cdecl CesiumGltfReader::ImageDecoder::readImage(class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::Ktx2TranscodeTargets const &)" (?readImage@ImageDecoder@CesiumGltfReader@@SA?AUImageReaderResult@2@AEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUKtx2TranscodeTargets@CesiumGltf@@@Z)
CesiumGltfReader.lib(ImageDecoder.obj) : error LNK2019: unresolved external symbol __imp_ktxTexture2_CreateFromMemory referenced in function "public: static struct CesiumGltfReader::ImageReaderResult __cdecl CesiumGltfReader::ImageDecoder::readImage(class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::Ktx2TranscodeTargets const &)" (?readImage@ImageDecoder@CesiumGltfReader@@SA?AUImageReaderResult@2@AEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUKtx2TranscodeTargets@CesiumGltf@@@Z)
CesiumGltfReader.lib(ImageDecoder.obj) : error LNK2019: unresolved external symbol __imp_ktxTexture2_GetNumComponents referenced in function "public: static struct CesiumGltfReader::ImageReaderResult __cdecl CesiumGltfReader::ImageDecoder::readImage(class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::Ktx2TranscodeTargets const &)" (?readImage@ImageDecoder@CesiumGltfReader@@SA?AUImageReaderResult@2@AEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUKtx2TranscodeTargets@CesiumGltf@@@Z)
CesiumGltfReader.lib(ImageDecoder.obj) : error LNK2019: unresolved external symbol __imp_ktxTexture2_NeedsTranscoding referenced in function "public: static struct CesiumGltfReader::ImageReaderResult __cdecl CesiumGltfReader::ImageDecoder::readImage(class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::Ktx2TranscodeTargets const &)" (?readImage@ImageDecoder@CesiumGltfReader@@SA?AUImageReaderResult@2@AEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUKtx2TranscodeTargets@CesiumGltf@@@Z)
CesiumGltfReader.lib(ImageDecoder.obj) : error LNK2019: unresolved external symbol __imp_ktxTexture2_TranscodeBasis referenced in function "public: static struct CesiumGltfReader::ImageReaderResult __cdecl CesiumGltfReader::ImageDecoder::readImage(class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::Ktx2TranscodeTargets const &)" (?readImage@ImageDecoder@CesiumGltfReader@@SA?AUImageReaderResult@2@AEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUKtx2TranscodeTargets@CesiumGltf@@@Z)
CesiumGltfReader.lib(ImageDecoder.obj) : error LNK2019: unresolved external symbol __imp_ktxErrorString referenced in function "public: static struct CesiumGltfReader::ImageReaderResult __cdecl CesiumGltfReader::ImageDecoder::readImage(class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::Ktx2TranscodeTargets const &)" (?readImage@ImageDecoder@CesiumGltfReader@@SA?AUImageReaderResult@2@AEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUKtx2TranscodeTargets@CesiumGltf@@@Z)
CesiumGltfReader.lib(decodeMeshOpt.obj) : error LNK2019: unresolved external symbol __imp_meshopt_decodeIndexBuffer referenced in function "int __cdecl CesiumGltfReader::`anonymous namespace'::decodeBufferView(void *,class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::ExtensionBufferViewExtMeshoptCompression const &)" (?decodeBufferView@?A0x993a0d7a@CesiumGltfReader@@YAHPEAXAEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUExtensionBufferViewExtMeshoptCompression@CesiumGltf@@@Z)
CesiumGltfReader.lib(decodeMeshOpt.obj) : error LNK2019: unresolved external symbol __imp_meshopt_decodeIndexSequence referenced in function "int __cdecl CesiumGltfReader::`anonymous namespace'::decodeBufferView(void *,class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::ExtensionBufferViewExtMeshoptCompression const &)" (?decodeBufferView@?A0x993a0d7a@CesiumGltfReader@@YAHPEAXAEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUExtensionBufferViewExtMeshoptCompression@CesiumGltf@@@Z)
CesiumGltfReader.lib(decodeMeshOpt.obj) : error LNK2019: unresolved external symbol __imp_meshopt_decodeVertexBuffer referenced in function "int __cdecl CesiumGltfReader::`anonymous namespace'::decodeBufferView(void *,class std::span<enum std::byte const ,-1> const &,struct CesiumGltf::ExtensionBufferViewExtMeshoptCompression const &)" (?decodeBufferView@?A0x993a0d7a@CesiumGltfReader@@YAHPEAXAEBV?$span@$$CBW4byte@std@@$0?0@std@@AEBUExtensionBufferViewExtMeshoptCompression@CesiumGltf@@@Z)
CesiumGltfReader.lib(decodeMeshOpt.obj) : error LNK2019: unresolved external symbol __imp_meshopt_decodeFilterOct referenced in function "void __cdecl CesiumGltfReader::`anonymous namespace'::decodeFilter(enum std::byte *,struct CesiumGltf::ExtensionBufferViewExtMeshoptCompression const &)" (?decodeFilter@?A0x993a0d7a@CesiumGltfReader@@YAXPEAW4byte@std@@AEBUExtensionBufferViewExtMeshoptCompression@CesiumGltf@@@Z)
CesiumGltfReader.lib(decodeMeshOpt.obj) : error LNK2019: unresolved external symbol __imp_meshopt_decodeFilterQuat referenced in function "void __cdecl CesiumGltfReader::`anonymous namespace'::decodeFilter(enum std::byte *,struct CesiumGltf::ExtensionBufferViewExtMeshoptCompression const &)" (?decodeFilter@?A0x993a0d7a@CesiumGltfReader@@YAXPEAW4byte@std@@AEBUExtensionBufferViewExtMeshoptCompression@CesiumGltf@@@Z)
CesiumGltfReader.lib(decodeMeshOpt.obj) : error LNK2019: unresolved external symbol __imp_meshopt_decodeFilterExp referenced in function "void __cdecl CesiumGltfReader::`anonymous namespace'::decodeFilter(enum std::byte *,struct CesiumGltf::ExtensionBufferViewExtMeshoptCompression const &)" (?decodeFilter@?A0x993a0d7a@CesiumGltfReader@@YAXPEAW4byte@std@@AEBUExtensionBufferViewExtMeshoptCompression@CesiumGltf@@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl spdlog::logger::log(struct spdlog::source_loc,enum spdlog::level::level_enum,class fmt::v11::basic_string_view<char>)" (__imp_?log@logger@spdlog@@QEAAXUsource_loc@2@W4level_enum@level@2@V?$basic_string_view@D@v11@fmt@@@Z) referenced in function "public: virtual bool __cdecl CesiumAsync::SqliteCache::clearAll(void)" (?clearAll@SqliteCache@CesiumAsync@@UEAA_NXZ)
Cesium3DTilesSelection.lib(RasterOverlayCollection.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl spdlog::logger::log(struct spdlog::source_loc,enum spdlog::level::level_enum,class fmt::v11::basic_string_view<char>)" (__imp_?log@logger@spdlog@@QEAAXUsource_loc@2@W4level_enum@level@2@V?$basic_string_view@D@v11@fmt@@@Z)
Cesium3DTilesSelection.lib(TilesetJsonLoader.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl spdlog::logger::log(struct spdlog::source_loc,enum spdlog::level::level_enum,class fmt::v11::basic_string_view<char>)" (__imp_?log@logger@spdlog@@QEAAXUsource_loc@2@W4level_enum@level@2@V?$basic_string_view@D@v11@fmt@@@Z)
Cesium3DTilesSelection.lib(CesiumIonTilesetLoader.obj) : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl spdlog::logger::log(struct spdlog::source_loc,enum spdlog::level::level_enum,class fmt::v11::basic_string_view<char>)" (__imp_?log@logger@spdlog@@QEAAXUsource_loc@2@W4level_enum@level@2@V?$basic_string_view@D@v11@fmt@@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_exec referenced in function "private: void __cdecl CesiumAsync::SqliteCache::createConnection(void)const " (?createConnection@SqliteCache@CesiumAsync@@AEBAXXZ)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_changes referenced in function "public: virtual bool __cdecl CesiumAsync::SqliteCache::prune(void)" (?prune@SqliteCache@CesiumAsync@@UEAA_NXZ)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_free referenced in function "private: void __cdecl CesiumAsync::SqliteCache::createConnection(void)const " (?createConnection@SqliteCache@CesiumAsync@@AEBAXXZ)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_open referenced in function "private: void __cdecl CesiumAsync::SqliteCache::createConnection(void)const " (?createConnection@SqliteCache@CesiumAsync@@AEBAXXZ)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_errstr referenced in function "public: virtual bool __cdecl CesiumAsync::SqliteCache::clearAll(void)" (?clearAll@SqliteCache@CesiumAsync@@UEAA_NXZ)
CesiumAsync.lib(SqliteHelper.obj) : error LNK2001: unresolved external symbol __imp_sqlite3_errstr
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_bind_blob referenced in function "public: virtual bool __cdecl CesiumAsync::SqliteCache::storeEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,__int64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct CesiumAsync::CaseInsensitiveCompare,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,unsigned short,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct CesiumAsync::CaseInsensitiveCompare,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,class std::span<enum std::byte const ,-1> const &)" (?storeEntry@SqliteCache@CesiumAsync@@UEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_J00AEBV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@UCaseInsensitiveCompare@CesiumAsync@@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@4@G2AEBV?$span@$$CBW4byte@std@@$0?0@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_bind_int referenced in function "public: virtual bool __cdecl CesiumAsync::SqliteCache::storeEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,__int64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct CesiumAsync::CaseInsensitiveCompare,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,unsigned short,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct CesiumAsync::CaseInsensitiveCompare,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,class std::span<enum std::byte const ,-1> const &)" (?storeEntry@SqliteCache@CesiumAsync@@UEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_J00AEBV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@UCaseInsensitiveCompare@CesiumAsync@@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@4@G2AEBV?$span@$$CBW4byte@std@@$0?0@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_bind_int64 referenced in function "public: virtual class std::optional<class CesiumAsync::CacheItem> __cdecl CesiumAsync::SqliteCache::getEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getEntry@SqliteCache@CesiumAsync@@UEBA?AV?$optional@VCacheItem@CesiumAsync@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_bind_text referenced in function "public: virtual class std::optional<class CesiumAsync::CacheItem> __cdecl CesiumAsync::SqliteCache::getEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getEntry@SqliteCache@CesiumAsync@@UEBA?AV?$optional@VCacheItem@CesiumAsync@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_clear_bindings referenced in function "public: virtual class std::optional<class CesiumAsync::CacheItem> __cdecl CesiumAsync::SqliteCache::getEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getEntry@SqliteCache@CesiumAsync@@UEBA?AV?$optional@VCacheItem@CesiumAsync@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_step referenced in function "public: virtual bool __cdecl CesiumAsync::SqliteCache::clearAll(void)" (?clearAll@SqliteCache@CesiumAsync@@UEAA_NXZ)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_column_blob referenced in function "public: virtual class std::optional<class CesiumAsync::CacheItem> __cdecl CesiumAsync::SqliteCache::getEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getEntry@SqliteCache@CesiumAsync@@UEBA?AV?$optional@VCacheItem@CesiumAsync@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_column_int referenced in function "public: virtual class std::optional<class CesiumAsync::CacheItem> __cdecl CesiumAsync::SqliteCache::getEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getEntry@SqliteCache@CesiumAsync@@UEBA?AV?$optional@VCacheItem@CesiumAsync@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_column_int64 referenced in function "public: virtual class std::optional<class CesiumAsync::CacheItem> __cdecl CesiumAsync::SqliteCache::getEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getEntry@SqliteCache@CesiumAsync@@UEBA?AV?$optional@VCacheItem@CesiumAsync@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_column_text referenced in function "public: virtual class std::optional<class CesiumAsync::CacheItem> __cdecl CesiumAsync::SqliteCache::getEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getEntry@SqliteCache@CesiumAsync@@UEBA?AV?$optional@VCacheItem@CesiumAsync@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_column_bytes referenced in function "public: virtual class std::optional<class CesiumAsync::CacheItem> __cdecl CesiumAsync::SqliteCache::getEntry(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?getEntry@SqliteCache@CesiumAsync@@UEBA?AV?$optional@VCacheItem@CesiumAsync@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
CesiumAsync.lib(SqliteCache.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_reset referenced in function "public: virtual bool __cdecl CesiumAsync::SqliteCache::clearAll(void)" (?clearAll@SqliteCache@CesiumAsync@@UEAA_NXZ)
CesiumAsync.lib(SqliteHelper.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_close_v2 referenced in function "public: void __cdecl CesiumAsync::DeleteSqliteConnection::operator()(struct sqlite3 *)" (??RDeleteSqliteConnection@CesiumAsync@@QEAAXPEAUsqlite3@@@Z)
CesiumAsync.lib(SqliteHelper.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_prepare_v2 referenced in function "public: static class std::unique_ptr<struct sqlite3_stmt,struct CesiumAsync::DeleteSqliteStatement> __cdecl CesiumAsync::SqliteHelper::prepareStatement(class std::unique_ptr<struct sqlite3,struct CesiumAsync::DeleteSqliteConnection> const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?prepareStatement@SqliteHelper@CesiumAsync@@SA?AV?$unique_ptr@Usqlite3_stmt@@UDeleteSqliteStatement@CesiumAsync@@@std@@AEBV?$unique_ptr@Usqlite3@@UDeleteSqliteConnection@CesiumAsync@@@4@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
CesiumAsync.lib(SqliteHelper.obj) : error LNK2019: unresolved external symbol __imp_sqlite3_finalize referenced in function "public: void __cdecl CesiumAsync::DeleteSqliteStatement::operator()(struct sqlite3_stmt *)" (??RDeleteSqliteStatement@CesiumAsync@@QEAAXPEAUsqlite3_stmt@@@Z)
CesiumRasterOverlays.lib(TileMapServiceRasterOverlay.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class tinyxml2::XMLElement * __cdecl tinyxml2::XMLNode::FirstChildElement(char const *)" (__imp_?FirstChildElement@XMLNode@tinyxml2@@QEAAPEAVXMLElement@2@PEBD@Z) referenced in function "public: class nonstd::expected_lite::expected<class CesiumUtility::IntrusivePointer<class CesiumRasterOverlays::RasterOverlayTileProvider>,class CesiumRasterOverlays::RasterOverlayLoadFailureDetails> __cdecl `public: virtual class CesiumAsync::Future<class nonstd::expected_lite::expected<class CesiumUtility::IntrusivePointer<class CesiumRasterOverlays::RasterOverlayTileProvider>,class CesiumRasterOverlays::RasterOverlayLoadFailureDetails> > __cdecl CesiumRasterOverlays::TileMapServiceRasterOverlay::createTileProvider(class CesiumAsync::AsyncSystem const &,class std::shared_ptr<class CesiumAsync::IAssetAccessor> const &,class std::shared_ptr<class CesiumUtility::CreditSystem> const &,class std::shared_ptr<class CesiumRasterOverlays::IPrepareRasterOverlayRendererResources> const &,class std::shared_ptr<class spdlog::logger> const &,class CesiumUtility::IntrusivePointer<class CesiumRasterOverlays::RasterOverlay const >)const '::`2'::<lambda_1>::operator()(class nonstd::expected_lite::expected<class std::unique_ptr<class tinyxml2::XMLDocument,struct std::default_delete<class tinyxml2::XMLDocument> >,class CesiumRasterOverlays::RasterOverlayLoadFailureDetails> &&)const " (??R<lambda_1>@?1??createTileProvider@TileMapServiceRasterOverlay@CesiumRasterOverlays@@UEBA?AV?$Future@V?$expected@V?$IntrusivePointer@VRasterOverlayTileProvider@CesiumRasterOverlays@@@CesiumUtility@@VRasterOverlayLoadFailureDetails@CesiumRasterOverlays@@@expected_lite@nonstd@@@CesiumAsync@@AEBVAsyncSystem@5@AEBV?$shared_ptr@VIAssetAccessor@CesiumAsync@@@std@@AEBV?$shared_ptr@VCreditSystem@CesiumUtility@@@8@AEBV?$shared_ptr@VIPrepareRasterOverlayRendererResources@CesiumRasterOverlays@@@8@AEBV?$shared_ptr@Vlogger@spdlog@@@8@V?$IntrusivePointer@$$CBVRasterOverlay@CesiumRasterOverlays@@@CesiumUtility@@@Z@QEBA?AV?$expected@V?$IntrusivePointer@VRasterOverlayTileProvider@CesiumRasterOverlays@@@CesiumUtility@@VRasterOverlayLoadFailureDetails@CesiumRasterOverlays@@@expected_lite@nonstd@@$$QEAV?$expected@V?$unique_ptr@VXMLDocument@tinyxml2@@U?$default_delete@VXMLDocument@tinyxml2@@@std@@@std@@VRasterOverlayLoadFailureDetails@CesiumRasterOverlays@@@expected_lite@nonstd@@@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: class tinyxml2::XMLElement const * __cdecl tinyxml2::XMLNode::FirstChildElement(char const *)const " (__imp_?FirstChildElement@XMLNode@tinyxml2@@QEBAPEBVXMLElement@2@PEBD@Z)
CesiumRasterOverlays.lib(TileMapServiceRasterOverlay.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class tinyxml2::XMLElement * __cdecl tinyxml2::XMLDocument::RootElement(void)" (__imp_?RootElement@XMLDocument@tinyxml2@@QEAAPEAVXMLElement@2@XZ) referenced in function "public: class nonstd::expected_lite::expected<class CesiumUtility::IntrusivePointer<class CesiumRasterOverlays::RasterOverlayTileProvider>,class CesiumRasterOverlays::RasterOverlayLoadFailureDetails> __cdecl `public: virtual class CesiumAsync::Future<class nonstd::expected_lite::expected<class CesiumUtility::IntrusivePointer<class CesiumRasterOverlays::RasterOverlayTileProvider>,class CesiumRasterOverlays::RasterOverlayLoadFailureDetails> > __cdecl CesiumRasterOverlays::TileMapServiceRasterOverlay::createTileProvider(class CesiumAsync::AsyncSystem const &,class std::shared_ptr<class CesiumAsync::IAssetAccessor> const &,class std::shared_ptr<class CesiumUtility::CreditSystem> const &,class std::shared_ptr<class CesiumRasterOverlays::IPrepareRasterOverlayRendererResources> const &,class std::shared_ptr<class spdlog::logger> const &,class CesiumUtility::IntrusivePointer<class CesiumRasterOverlays::RasterOverlay const >)const '::`2'::<lambda_1>::operator()(class nonstd::expected_lite::expected<class std::unique_ptr<class tinyxml2::XMLDocument,struct std::default_delete<class tinyxml2::XMLDocument> >,class CesiumRasterOverlays::RasterOverlayLoadFailureDetails> &&)const " (??R<lambda_1>@?1??createTileProvider@TileMapServiceRasterOverlay@CesiumRasterOverlays@@UEBA?AV?$Future@V?$expected@V?$IntrusivePointer@VRasterOverlayTileProvider@CesiumRasterOverlays@@@CesiumUtility@@VRasterOverlayLoadFailureDetails@CesiumRasterOverlays@@@expected_lite@nonstd@@@CesiumAsync@@AEBVAsyncSystem@5@AEBV?$shared_ptr@VIAssetAccessor@CesiumAsync@@@std@@AEBV?$shared_ptr@VCreditSystem@CesiumUtility@@@8@AEBV?$shared_ptr@VIPrepareRasterOverlayRendererResources@CesiumRasterOverlays@@@8@AEBV?$shared_ptr@Vlogger@spdlog@@@8@V?$IntrusivePointer@$$CBVRasterOverlay@CesiumRasterOverlays@@@CesiumUtility@@@Z@QEBA?AV?$expected@V?$IntrusivePointer@VRasterOverlayTileProvider@CesiumRasterOverlays@@@CesiumUtility@@VRasterOverlayLoadFailureDetails@CesiumRasterOverlays@@@expected_lite@nonstd@@$$QEAV?$expected@V?$unique_ptr@VXMLDocument@tinyxml2@@U?$default_delete@VXMLDocument@tinyxml2@@@std@@@std@@VRasterOverlayLoadFailureDetails@CesiumRasterOverlays@@@expected_lite@nonstd@@@Z)
godot3dtiles\bin\Godot3DTiles.windows.template_debug.x86_64.dll : fatal error LNK1120: 36 unresolved externals
scons: *** [godot3dtiles\bin\Godot3DTiles.windows.template_debug.x86_64.dll] Error 1120
scons: building terminated because of errors.
```

</details>

---
# Option 1: Use compiledb=yes for IntelliSense
> This generates a `compile_commands.json` file, which you can import into Visual Studio 2022 using the CMake Tools or Clang Power Tools extension to enable IntelliSense and navigation.

### Not work
`scons platform=windows arch=x64 compileTarget=extension  compiledb=yes buildCesium=true`

**Comment by GeorgeS2019** [comment]
## Option 2a: Manually Create a VS2022 Project` .vcxproj `Template

> a minimal MyProject.vcxproj file tailored for a typical GDExtension project in C++. You’ll need to adjust paths and flags as needed
```xml
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>

  <PropertyGroup Label="Globals">
    <ProjectGuid>{YOUR-GUID-HERE}</ProjectGuid>
    <Keyword>Win32Proj</Keyword>
    <RootNamespace>MyGodotExtension</RootNamespace>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>

  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>

  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />

  <ItemGroup>
    <ClCompile Include="src\my_extension.cpp" />
  </ItemGroup>

  <ItemGroup>
    <ClInclude Include="include\my_extension.h" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="godot-cpp.lib">
      <HintPath>path\to\your\godot-cpp\build\libgodot-cpp.windows.debug.64.lib</HintPath>
    </Reference>
  </ItemGroup>

  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
</Project>
```

## Option 2b: Setting Up compile_commands.json in VS2022

**Comment by GeorgeS2019** [comment]
## Within Godot-cpp

`scons platform=windows arch=x64 target=template_release debug_crt=yes`

**Comment by GeorgeS2019** [comment]
https://github.com/godotengine/godot-cpp/issues/1327

**Comment by GeorgeS2019** [comment]
### Within godot-cpp

```
cmake -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 17 2022" .
cmake --build . --verbose --config Release
```

![Image](https://github.com/user-attachments/assets/f71f3c5f-1bed-4225-ae58-692b829d924f)
